version: 2.1

executors:
  docker-executor:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # SonarScanner Docker image

jobs:
  frontend:
    executor: docker-executor
    steps:
      - checkout  # Check out the source code
      - run:
          name: Navigate to frontend directory and Install Dependencies
          command: |
            cd register.login/Frontend
            npm install
      - run:
          name: Run SonarQube Scan for Frontend
          command: |
            sonar-scanner -Dsonar.projectKey=ST10204001_ST10096757_APDS7311_International_Payments_Portal \
              -Dsonar.organization=st10204001 \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.branch.name=main
      - run:
          name: Run SonarQube Scan for Backend
          command: |
            sonar-scanner -Dsonar.projectKey=ST10204001_ST10096757_APDS7311_International_Payments_Portal \
              -Dsonar.organization=st10204001 \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.branch.name=main

  backend:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Navigate to backend directory and Install Dependencies
          command: |
            cd register.login/Backend
            npm install
      - run:
          name: Run SonarQube Scan for Backend
          command: |
            sonar-scanner -Dsonar.projectKey=ST10204001_ST10096757_APDS7311_International_Payments_Portal \
              -Dsonar.organization=st10204001 \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.branch.name=main

workflows:
  version: 2
  sonar_scan:
    jobs:
      - frontend
      - backend
