version: 2.1

executors:
  docker-executor:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # SonarScanner Docker image

jobs:
  sonarqube:
    executor: docker-executor
    steps:
      - checkout  # Check out the source code
      - run:
          name: Install Dependencies (if needed)
          command: |
            npm install

      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  sonarqbe_scan:
    jobs:
      - sonarqube
