version: 2.1

executors:
  docker-executor:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # SonarScanner Docker image

jobs:
  frontend:
    executor: docker-executor
    steps:
      - checkout  # Check out the source code
      - run:
          name: List files for debugging
          command: ls -R  # Recursively list files to verify directory structure
      - run:
          name: Navigate to frontend directory and Install Dependencies
          command: |
            cd register.login/Frontend
            npm install

      - run:
          name: Run SonarQube Scan for Frontend
          command: |
            sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN

  backend:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Navigate to backend directory and Install Dependencies
          command: |
            cd register.login/Backend 
            npm install

      - run:
          name: Run SonarQube Scan for Backend
          command: |
            sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  sonar_scan:
    jobs:
      - frontend
      - backend
