on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: List directory contents for debugging
      - name: List directory contents
        run: ls -R

      # Step 3: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 4: Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd register.login/Backend
          npm install

      # Step 5: Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd register.login/Frontend
          npm install

      # Step 6: Clean and reinstall frontend dependencies if necessary
      - name: Clean and reinstall frontend dependencies
        run: |
          cd register.login/Frontend
          rm -rf node_modules package-lock.json  # Clean up old modules and lock file
          npm install  # Reinstall fresh dependencies

      # Step 7: Ensure react-scripts has execute permissions
      - name: Ensure react-scripts has execute permissions
        run: |
          cd register.login/Frontend
          chmod +x ./node_modules/.bin/react-scripts  # Ensure react-scripts is executable

      # Step 8: Build React App while ignoring warnings
      - name: Build React App (ignore warnings)
        run: |
          cd register.login/Frontend
          CI=false npm run build || echo "Ignoring warnings and continuing build"

      # Step 9: Set SSL options for backend
      - name: Set SSL options
        run: |
          cd register.login/Backend
          ls -l ./keys  # List the contents of the keys directory
          chmod 644 ./keys/server.key
          chmod 644 ./keys/server.crt

      # Step 10: Check SSL configuration
      - name: Check SSL configuration
        run: |
          cd register.login/Backend
          if [ ! -f ./keys/server.key ] || [ ! -f ./keys/server.crt ]; then
            echo "SSL certificate or key missing" && exit 1
          fi

      # Step 11: Start the HTTPS server
      - name: Start HTTPS server
        run: |
          cd register.login/Backend
          node server.js &
          sleep 30  # Wait for the server to start

      # Step 12: Check if the HTTPS server is running on port 5000
      - name: Check HTTPS server status
        run: |
          echo "Checking if HTTPS server is running on port 5000..."
          curl -v https://localhost:5000 --insecure || exit 1

      # Step 13: Run server integration check
      - name: Run server check
        run: |
          curl -f https://localhost:5000 --insecure || exit 1

      # Step 14: Check for protection against additional attacks
      - name: Security Attack Checks
        run: |
          cd register.login/Backend
          # Check for Clickjacking Protection
          if ! grep -q "frameguard" src/App.js; then
            echo "Clickjacking protection missing (Helmet's frameguard)" && exit 1
          fi
          # Check for Session Jacking Protection
          if ! grep -q "cookieSession" src/App.js; then
            echo "Session hijacking protection missing (cookie-session middleware)" && exit 1
          fi
          # Check for SQL Injection Prevention
          if ! grep -q "findOne(" src/App.js; then
            echo "SQL Injection protection missing (use Mongoose methods like findOne)" && exit 1
          fi
          # Check for Cross-Site Scripting (XSS) Protection
          if ! grep -q "xss-clean" src/App.js; then
            echo "XSS protection missing (xss-clean middleware)" && exit 1
          fi
          # Check for Man-in-the-Middle Attack Protection
          if ! grep -q "Strict-Transport-Security" src/App.js; then
            echo "HSTS header missing (use Helmet to enforce Strict-Transport-Security)" && exit 1
          fi
          # DDoS Protection (Rate Limiting and Network Throttling)
          if ! grep -q "express-rate-limit" src/App.js; then
            echo "DDoS protection missing (express-rate-limit middleware)" && exit 1
          fi

      # Step 15: Upload results 
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
