name: SonarCloud Analysis

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Set the JDK distribution (Temurin is recommended)
          java-package: 'jdk'
          check-latest: false

      # Step 3: Run SonarCloud Analysis
      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=ST10204001_ST10096757_APDS7311_International_Payments_Portal
            -Dsonar.organization=st10204001
            -Dsonar.login=$6357971180c41865f5f19b083e030b5636059f8b
            -Dsonar.branch.name=main
            -Dsonar.sources=register.login/Backend  # Specify your backend source directory
        env:
          SONAR_TOKEN: 6357971180c41865f5f19b083e030b5636059f8b
