   name: SonarQube Scan

   on:
     push:
       branches:
         - main
     pull_request:
       branches:
         - main

   jobs:
     sonar:
       name: Run SonarQube analysis
       runs-on: ubuntu-latest

       steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Set up JDK 11
           uses: actions/setup-java@v2
           with:
             java-version: '11'

         - name: Cache SonarQube dependencies
           uses: actions/cache@v2
           with:
             path: ~/.sonar/cache
             key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}

         - name: SonarQube Scan
           uses: sonarsource/sonarcloud-github-action@main
           with:
             organization: ${{ secrets.SONAR_ORG }}
             projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
             token: ${{ secrets.SONAR_TOKEN }}
